### ISSUE TITLE
gulp-autoprefixer causes this error with gulp-ruby-sass

### ISSUE THREAD

**Issue by alechance** [tsevdos/Gulp-boilerplate-for-web-designers#1]
```
[11:57:39] Starting 'styles'...
[11:57:40] gulp-ruby-sass: directory
[11:57:40] gulp-ruby-sass: write main.css
      write main.css.map

events.js:72
        throw er; // Unhandled 'error' event
              ^
```

Any ideas why? Thanks!

**Comment by tsevdos** [comment]
Hello @alechance 

Try to comment out this line of code `.pipe(autoprefixer('last 2 version', 'safari 5', 'ie 8', 'ie 9', 'opera 12.1', 'ios 6', 'android 4'))`(**gulpfile.js**). I'm planning to update the entire repo when I'll find the time...
